import { logIn } from "./login.js";
logIn();
import { validation } from "./regex.js";
validation();
import { overlay } from "./overlay.js";
overlay();
import { showHide } from "./showHide.js";
showHide();
import { cookieNotification } from "./cookiesNotification.js";
cookieNotification();
